controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

mentionLegale:
    path: '/mentionLegale/{id}'
    controller: 'App\Controller\LegalController::route1'
    methods: ['GET']

app_legal_route0:
    path: /Interaction
    controller: App\Controller\LegalController::route0
    methods: ['GET', 'POST']

recapitulatif:
    path: '/recapitulatif/{id}'
    controller: App\Controller\DevisController::recapitulatifAction
    methods: GET